### ISSUE TITLE
CT: Cannot read property 'removeInputListener' of null

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/masses-and-springs#331]
```
masses-and-springs : fuzz : built : run
Uncaught TypeError: Cannot read property 'removeInputListener' of null
TypeError: Cannot read property 'removeInputListener' of null
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/masses-and-springs/build/phet/masses-and-springs_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzzMouse&fuzzTouch:964:707160)
    at emit1 (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/masses-and-springs/build/phet/masses-and-springs_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzzMouse&fuzzTouch:964:19124)
    at e.release (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/masses-and-springs/build/phet/masses-and-springs_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzzMouse&fuzzTouch:964:708890)
    at Object.up (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/masses-and-springs/build/phet/masses-and-springs_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzzMouse&fuzzTouch:964:706013)
    at e.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/masses-and-springs/build/phet/masses-and-springs_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzzMouse&fuzzTouch:964:824456)
    at e.dispatchEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/masses-and-springs/build/phet/masses-and-springs_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzzMouse&fuzzTouch:964:824162)
    at e.upEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/masses-and-springs/build/phet/masses-and-springs_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzzMouse&fuzzTouch:964:822779)
    at e.touchEnd (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/masses-and-springs/build/phet/masses-and-springs_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzzMouse&fuzzTouch:964:820064)
    at e.touchEnd (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/masses-and-springs/build/phet/masses-and-springs_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzzMouse&fuzzTouch:964:1176554)
    at touchEndAction (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/masses-and-springs/build/phet/masses-and-springs_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzzMouse&fuzzTouch:964:1174516)
Approximately 9/13/2018, 5:26:41 AM
masses-and-springs : fuzz : require.js-canvas : run
Uncaught Error: Assertion failed
Error: Assertion failed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/assert/js/assert.js:22:13)
    at Object.cancel (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/scenery/js/listeners/PressListener.js?bust=1536848534526:229:19)
    at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/scenery/js/input/Input.js?bust=1536848534526:1353:27)
    at Input.dispatchEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/scenery/js/input/Input.js?bust=1536848534526:1309:12)
    at Input.cancelEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/scenery/js/input/Input.js?bust=1536848534526:1169:12)
    at Input.touchCancel (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/scenery/js/input/Input.js?bust=1536848534526:737:14)
    at InputFuzzer.touchCancel (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/scenery/js/input/InputFuzzer.js?bust=1536848534526:259:27)
    at InputFuzzer.touchCancelAction (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/scenery/js/input/InputFuzzer.js?bust=1536848534526:66:12)
    at InputFuzzer.fuzzEvents (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/scenery/js/input/InputFuzzer.js?bust=1536848534526:114:9)
    at Sim.stepSimulation (https://bayes.colorado.edu/continuous-testing/snapshot-1536838001842/joist/js/Sim.js?bust=1536848534526:818:26)
Approximately 9/13/2018, 5:26:41 AM
```

**Comment by phet-steele** [comment]
@Denz1994 are we ignoring this for 1.0?

**Comment by Denz1994** [comment]
@ariel-phet mentioned via slack 1.0 these issues (along with #328) shouldn't stop publication. We can revisit for a maintenance release if stability/usability are an issue.

**Comment by KatieWoe** [comment]
Adding some assertion failed instances to this issue. @Denz1994 
```
masses-and-springs : fuzz : built : run
Uncaught TypeError: Cannot read property 'removeInputListener' of null
TypeError: Cannot read property 'removeInputListener' of null
    at e.onRelease (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/masses-and-springs/build/phet/masses-and-springs_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz:964:611204)
    at e.value (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/masses-and-springs/build/phet/masses-and-springs_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz:964:27013)
    at e.release (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/masses-and-springs/build/phet/masses-and-springs_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz:964:610219)
    at e.pointerUp (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/masses-and-springs/build/phet/masses-and-springs_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz:964:611575)
    at e.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/masses-and-springs/build/phet/masses-and-springs_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz:964:842294)
    at e.dispatchEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/masses-and-springs/build/phet/masses-and-springs_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz:964:842000)
    at e.upEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/masses-and-springs/build/phet/masses-and-springs_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz:964:840617)
    at e.listener (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/masses-and-springs/build/phet/masses-and-springs_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz:964:833308)
    at e.value (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/masses-and-springs/build/phet/masses-and-springs_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz:964:27013)
    at e.touchEnd (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/masses-and-springs/build/phet/masses-and-springs_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz:964:839021)
id: Bayes Chrome
Approximately 10/21/2018, 10:00:35 PM
masses-and-springs : fuzz : require.js : run
Uncaught Error: Assertion failed
Error: Assertion failed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/assert/js/assert.js:22:13)
    at PressListener.pointerUp (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/listeners/PressListener.js?bust=1540187664352:575:17)
    at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/input/Input.js?bust=1540187664352:1488:27)
    at Input.dispatchEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/input/Input.js?bust=1540187664352:1444:12)
    at Input.upEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/input/Input.js?bust=1540187664352:1207:12)
    at Emitter.listener (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/input/Input.js?bust=1540187664352:381:16)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/axon/js/Emitter.js?bust=1540187664352:187:53)
    at Input.touchEnd (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/input/Input.js?bust=1540187664352:891:30)
    at InputFuzzer.touchEnd (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/input/InputFuzzer.js?bust=1540187664352:246:27)
    at InputFuzzer.touchEndAction (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/input/InputFuzzer.js?bust=1540187664352:61:12)
id: Bayes Chrome
Approximately 10/21/2018, 10:00:35 PM
masses-and-springs : fuzz : require.js : run
Uncaught Error: Assertion failed
Error: Assertion failed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/assert/js/assert.js:22:13)
    at PressListener.pointerUp (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/listeners/PressListener.js?bust=1540202971232:575:17)
    at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/input/Input.js?bust=1540202971232:1488:27)
    at Input.dispatchEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/input/Input.js?bust=1540202971232:1444:12)
    at Input.upEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/input/Input.js?bust=1540202971232:1207:12)
    at Emitter.listener (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/input/Input.js?bust=1540202971232:381:16)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/axon/js/Emitter.js?bust=1540202971232:187:53)
    at Input.touchEnd (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/input/Input.js?bust=1540202971232:891:30)
    at InputFuzzer.touchEnd (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/input/InputFuzzer.js?bust=1540202971232:246:27)
    at InputFuzzer.touchEndAction (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/input/InputFuzzer.js?bust=1540202971232:61:12)
id: Bayes Chrome
Approximately 10/21/2018, 10:00:35 PM
masses-and-springs : fuzz : require.js-canvas : run
Uncaught Error: Assertion failed
Error: Assertion failed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/assert/js/assert.js:22:13)
    at PressListener.pointerUp (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/listeners/PressListener.js?bust=1540210649556:575:17)
    at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/input/Input.js?bust=1540210649556:1488:27)
    at Input.dispatchEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/input/Input.js?bust=1540210649556:1444:12)
    at Input.upEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/input/Input.js?bust=1540210649556:1207:12)
    at Emitter.listener (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/input/Input.js?bust=1540210649556:381:16)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/axon/js/Emitter.js?bust=1540210649556:187:53)
    at Input.touchEnd (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/input/Input.js?bust=1540210649556:891:30)
    at InputFuzzer.touchEnd (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/input/InputFuzzer.js?bust=1540210649556:246:27)
    at InputFuzzer.touchEndAction (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/input/InputFuzzer.js?bust=1540210649556:61:12)
id: Bayes Chrome
Approximately 10/21/2018, 10:00:35 PM
masses-and-springs : fuzz : require.js-canvas : run
Uncaught Error: Assertion failed
Error: Assertion failed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/assert/js/assert.js:22:13)
    at PressListener.pointerUp (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/listeners/PressListener.js?bust=1540216962312:575:17)
    at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/input/Input.js?bust=1540216962312:1488:27)
    at Input.dispatchEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/input/Input.js?bust=1540216962312:1444:12)
    at Input.upEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/input/Input.js?bust=1540216962312:1207:12)
    at Emitter.listener (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/input/Input.js?bust=1540216962312:381:16)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/axon/js/Emitter.js?bust=1540216962312:187:53)
    at Input.touchEnd (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/input/Input.js?bust=1540216962312:891:30)
    at InputFuzzer.touchEnd (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/input/InputFuzzer.js?bust=1540216962312:246:27)
    at InputFuzzer.touchEndAction (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/input/InputFuzzer.js?bust=1540216962312:61:12)
id: Bayes Chrome
Approximately 10/21/2018, 10:00:35 PM
masses-and-springs : xss-fuzz : run
Uncaught Error: Assertion failed
Error: Assertion failed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/assert/js/assert.js:22:13)
    at PressListener.pointerUp (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/listeners/PressListener.js?bust=1540188351181:575:17)
    at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/input/Input.js?bust=1540188351181:1488:27)
    at Input.dispatchEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/input/Input.js?bust=1540188351181:1444:12)
    at Input.upEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/input/Input.js?bust=1540188351181:1207:12)
    at Emitter.listener (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/input/Input.js?bust=1540188351181:381:16)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/axon/js/Emitter.js?bust=1540188351181:187:53)
    at Input.touchEnd (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/input/Input.js?bust=1540188351181:891:30)
    at InputFuzzer.touchEnd (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/input/InputFuzzer.js?bust=1540188351181:246:27)
    at InputFuzzer.touchEndAction (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/input/InputFuzzer.js?bust=1540188351181:61:12)
id: Bayes Chrome
Approximately 10/21/2018, 10:00:35 PM
masses-and-springs : xss-fuzz : run
Uncaught Error: Assertion failed
Error: Assertion failed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/assert/js/assert.js:22:13)
    at PressListener.pointerUp (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/listeners/PressListener.js?bust=1540204857723:575:17)
    at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/input/Input.js?bust=1540204857723:1488:27)
    at Input.dispatchEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/input/Input.js?bust=1540204857723:1444:12)
    at Input.upEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/input/Input.js?bust=1540204857723:1207:12)
    at Emitter.listener (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/input/Input.js?bust=1540204857723:381:16)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/axon/js/Emitter.js?bust=1540204857723:187:53)
    at Input.touchEnd (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/input/Input.js?bust=1540204857723:891:30)
    at InputFuzzer.touchEnd (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/input/InputFuzzer.js?bust=1540204857723:246:27)
    at InputFuzzer.touchEndAction (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/input/InputFuzzer.js?bust=1540204857723:61:12)
id: Bayes Chrome
Approximately 10/21/2018, 10:00:35 PM
masses-and-springs : xss-fuzz : run
Uncaught Error: Assertion failed
Error: Assertion failed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/assert/js/assert.js:22:13)
    at PressListener.pointerUp (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/listeners/PressListener.js?bust=1540212208016:575:17)
    at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/input/Input.js?bust=1540212208016:1488:27)
    at Input.dispatchEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/input/Input.js?bust=1540212208016:1444:12)
    at Input.upEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/input/Input.js?bust=1540212208016:1207:12)
    at Emitter.listener (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/input/Input.js?bust=1540212208016:381:16)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/axon/js/Emitter.js?bust=1540212208016:187:53)
    at Input.touchEnd (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/input/Input.js?bust=1540212208016:891:30)
    at InputFuzzer.touchEnd (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/input/InputFuzzer.js?bust=1540212208016:246:27)
    at InputFuzzer.touchEndAction (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/scenery/js/input/InputFuzzer.js?bust=1540212208016:61:12)
id: Bayes Chrome
Approximately 10/21/2018, 10:00:35 PM
```

**Comment by Denz1994** [comment]
Closing as described in https://github.com/phetsims/masses-and-springs/issues/336.
