### ISSUE TITLE
Automated Testing Errors

### ISSUE THREAD

**Issue by phet-steele** [phetsims/masses-and-springs#9]
fuzztesting build, on phettest:

```
Uncaught TypeError: Cannot read property 'node' of null
TypeError: Cannot read property 'node' of null
    at new n (http://phettest.colorado.edu/masses-and-springs/build/masses-and-springs_en.html?ea&postMessageOnLoad&postMessageOnError&fuzzMouse=100:501:4258)
    at Array.x (http://phettest.colorado.edu/masses-and-springs/build/masses-and-springs_en.html?ea&postMessageOnLoad&postMessageOnError&fuzzMouse=100:501:3199)
    at e.i.emit2 (http://phettest.colorado.edu/masses-and-springs/build/masses-and-springs_en.html?ea&postMessageOnLoad&postMessageOnError&fuzzMouse=100:492:7833)
    at e.n._notifyObservers (http://phettest.colorado.edu/masses-and-springs/build/masses-and-springs_en.html?ea&postMessageOnLoad&postMessageOnError&fuzzMouse=100:492:9751)
    at e.n._setAndNotifyObservers (http://phettest.colorado.edu/masses-and-springs/build/masses-and-springs_en.html?ea&postMessageOnLoad&postMessageOnError&fuzzMouse=100:492:9609)
    at e.n.set (http://phettest.colorado.edu/masses-and-springs/build/masses-and-springs_en.html?ea&postMessageOnLoad&postMessageOnError&fuzzMouse=100:492:9350)
    at l (http://phettest.colorado.edu/masses-and-springs/build/masses-and-springs_en.html?ea&postMessageOnLoad&postMessageOnError&fuzzMouse=100:503:27017)
    at s.start (http://phettest.colorado.edu/masses-and-springs/build/masses-and-springs_en.html?ea&postMessageOnLoad&postMessageOnError&fuzzMouse=100:503:27160)
    at e.i.startDrag (http://phettest.colorado.edu/masses-and-springs/build/masses-and-springs_en.html?ea&postMessageOnLoad&postMessageOnError&fuzzMouse=100:503:24057)
    at e.i.tryToSnag (http://phettest.colorado.edu/masses-and-springs/build/masses-and-springs_en.html?ea&postMessageOnLoad&postMessageOnError&fuzzMouse=100:503:24469)
```

**Comment by phet-steele** [comment]
fuzztesting requirejs:

```
Uncaught Error: Assertion failed: minimum spring constant must be positive : undefined
Error: Assertion failed: minimum spring constant must be positive : undefined
    at window.assertions.assertFunction (http://phettest.colorado.edu/assert/js/assert.js:23:13)
    at new Spring (http://phettest.colorado.edu/masses-and-springs/js/masses-and-springs/model/Spring.js?bust=1455558613992:31:15)
    at new MassesAndSpringsModel (http://phettest.colorado.edu/masses-and-springs/js/masses-and-springs/model/MassesAndSpringsModel.js?bust=1455558613992:26:7)
    at MassesAndSpringsScreen.Screen.call.backgroundColor [as createModel] (http://phettest.colorado.edu/masses-and-springs/js/masses-and-springs/MassesAndSpringsScreen.js?bust=1455558613992:30:27)
    at MassesAndSpringsScreen.inherit.initializeModel (http://phettest.colorado.edu/joist/js/Screen.js?bust=1455558613992:104:26)
    at MassesAndSpringsScreen.inherit.initializeModelAndView (http://phettest.colorado.edu/joist/js/Screen.js?bust=1455558613992:124:12)
    at http://phettest.colorado.edu/joist/js/Sim.js?bust=1455558613992:422:14
    at Function.St (http://phettest.colorado.edu/sherpa/lib/lodash-2.4.1.min.js?bust=1455558613992:23:149)
    at new Sim (http://phettest.colorado.edu/joist/js/Sim.js?bust=1455558613992:420:7)
    at http://phettest.colorado.edu/masses-and-springs/js/masses-and-springs-main.js?bust=1455558613992:39:15
```

**Comment by phet-steele** [comment]
fuzztesting requirejs:

```
Uncaught Error: Assertion failed: undefined
Error: Assertion failed: undefined
    at window.assertions.assertFunction (http://phettest.colorado.edu/assert/js/assert.js:23:13)
    at new RulerNode (http://phettest.colorado.edu/scenery-phet/js/RulerNode.js?bust=1458237940831:68:15)
    at new DraggableRulerNode (http://phettest.colorado.edu/masses-and-springs/js/masses-and-springs/view/DraggableRulerNode.js?bust=1458237940831:38:20)
    at new MassesAndSpringsScreenView (http://phettest.colorado.edu/masses-and-springs/js/masses-and-springs/view/MassesAndSpringsScreenView.js?bust=1458237940831:93:20)
    at MassesAndSpringsScreen.Screen.call.backgroundColor [as createView] (http://phettest.colorado.edu/masses-and-springs/js/masses-and-springs/MassesAndSpringsScreen.js?bust=1458237940831:31:34)
    at MassesAndSpringsScreen.inherit.initializeView (http://phettest.colorado.edu/joist/js/Screen.js?bust=1458237940831:114:25)
    at MassesAndSpringsScreen.inherit.initializeModelAndView (http://phettest.colorado.edu/joist/js/Screen.js?bust=1458237940831:125:12)
    at http://phettest.colorado.edu/joist/js/Sim.js?bust=1458237940831:425:14
    at Function.St (http://phettest.colorado.edu/sherpa/lib/lodash-2.4.1.min.js?bust=1458237940831:23:149)
    at new Sim (http://phettest.colorado.edu/joist/js/Sim.js?bust=1458237940831:423:7)
```

**Comment by phet-steele** [comment]
Last error occurred again on 3/22. See #11.

**Comment by phet-steele** [comment]
Third occurrence of the last error on 3/29.

**Comment by mattpen** [comment]
@phet-steele - I fixed the assert error for the 2nd and 3rd errors above.  I couldn't recreate the first, is it still occurring?

**Comment by phet-steele** [comment]
@mattpen I can't either, I'll keep an eye out for it.
